<h2 style='color:purple' align='center'>Naive Bayes Part 2:Spam Detection of emails</h2>

In [1]:
import pandas as pd
df=pd.read_csv("spam.csv")
# this dataset is downloaded from Kaggle

In [2]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df['Spam']=df.Category.apply(lambda x : 1 if x=='spam' else 0)

In [4]:
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X=cv.fit_transform(df.Message)

In [12]:
X

<5572x8709 sparse matrix of type '<class 'numpy.int64'>'
	with 74098 stored elements in Compressed Sparse Row format>

In [13]:
type(X)

scipy.sparse.csr.csr_matrix

In [14]:
X.toarray()[:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
Y=df.Spam

In [16]:
Y.head()

0    0
1    0
2    1
3    0
4    0
Name: Spam, dtype: int64

Types of naive bayes classifiers: REFER GREEN COPY

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y)

In [18]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()

In [19]:
model.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [20]:
model.score(X_test,y_test)

0.9755922469490309

To check whether the following emails are spam or not

In [21]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [22]:
mail=cv.transform(emails)

In [23]:
model.predict(mail)

array([0, 1], dtype=int64)

**Sklearn Pipeline**

In [29]:
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('cvv', CountVectorizer()),
    ('nbb', MultinomialNB())
]
)

In [30]:
from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(df.Message,df.Spam,test_size=0.2)

In [31]:
clf.fit(X1_train,y1_train)

Pipeline(memory=None,
         steps=[('cvv',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nbb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [32]:
clf.score(X1_test,y1_test)

0.9856502242152466

In [33]:
clf.predict(emails)

array([0, 1], dtype=int64)