# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

This will print the version of tensorflow, we are using

In [3]:
tf.__version__

'2.0.0'

## PART 1:  Data Preprocessing

In [4]:
dataset=pd.read_csv("Churn_Modelling.csv")

### This data set contains details of a bank's customers and the target variable is a binary variable reflecting the fact whether the customer left the bank or not

In [5]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [6]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(y)

[1 0 1 ... 1 1 0]


##### Label Encoding the "Gender" column

In [9]:
X[:, 2]

array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
      dtype=object)

In [10]:
X[:, 2:3]

array([['Female'],
       ['Female'],
       ['Female'],
       ...,
       ['Female'],
       ['Male'],
       ['Female']], dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [12]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

#### One Hot Encoding the "Geography" column

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X=ct.fit_transform(X)

In [14]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [15]:
X.shape

(10000, 12)

### Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [17]:
X=sc.fit_transform(X)

In [18]:
print(X)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


### Splitting the dataset into the Training set and Test set

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

In [20]:
from keras.models import Sequential
from keras.layers import Dense, Activation

Using TensorFlow backend.


model=sequential([L1,          L2,             L3])

The first layer and only the first layer needs to know the what i/p shape should it expect

L1 = the input layer and the first hidden layer

L2 =  the second hidden layer

L3 = O/P layer

In [21]:
model=Sequential([Dense(units=6,input_shape=(12,), activation='relu'),Dense(units=6, activation='relu'),Dense(units=1, activation='sigmoid')])

#####  units : the number of neurons or nodes in the current layer (hidden layer)
##### input_shape: the dimension of input, as X contains 12 feautres   
##### activation for hidden layers : the activation function applied to each node. ”relu” stands for Rectified Linear


##### output layer: Here we have a single output layer
##### Sigmoid activation functions for  output layer : Because o/p is binary(0/1) , i.e Yes or NO

In [22]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 78        
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 7         
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________


In [23]:
## oops=Sequential([Dense(units=6,input_dim=12, activation='relu'),Dense(units=6, activation='relu'),Dense(units=1, activation='sigmoid')])

In [24]:
## oops.summary()

## Part 3 - Training the ANN

### Compiling the ANN

In [25]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

##### Optimizer : Adam optimizer can perfrom stochastic gradient - helps you adjust the weight of edges as you are doing the training

##### Loss : to compute the difference b/w actual and predicted
##### When predicting a binary outcome, the loss function should always be binary_crossentropy 
##### For prediction of an o/p having categorical values , use sparse_categorical_crossentropy 

##### Metrics: the metric used to measure the accuracy of the model

### Training the ANN on the Training set

In [26]:
len(X_train)

8000

Assume you have a dataset with 200 samples (rows of data) and you choose a batch size of 5 and 1,000 epochs.

This means that the dataset will be divided into 40 batches, each with five samples. The model weights will be updated after each batch of five samples.

This also means that one epoch will involve 40 batches or 40 updates to the model.

With 1,000 epochs, the model will be exposed to or pass through the whole dataset 1,000 times. That is a total of 40,000 batches during the entire training process.

In [28]:
model.fit(X_train, y_train, batch_size = 32, epochs = 100) # classic value of batchsize chosen is 32

Epoch 1/100
8000/8000 [==============================] - 0s 54us/step - loss: 0.4804 - accuracy: 0.8016
Epoch 2/100
8000/8000 [==============================] - 0s 55us/step - loss: 0.4419 - accuracy: 0.8062
Epoch 3/100
8000/8000 [==============================] - 0s 53us/step - loss: 0.4258 - accuracy: 0.8130
Epoch 4/100
8000/8000 [==============================] - 0s 54us/step - loss: 0.4124 - accuracy: 0.8215
Epoch 5/100
8000/8000 [==============================] - 0s 52us/step - loss: 0.3997 - accuracy: 0.8284
Epoch 6/100
8000/8000 [==============================] - 0s 51us/step - loss: 0.3864 - accuracy: 0.8350
Epoch 7/100
8000/8000 [==============================] - 0s 53us/step - loss: 0.3746 - accuracy: 0.8429
Epoch 8/100
8000/8000 [==============================] - 0s 53us/step - loss: 0.3643 - accuracy: 0.8496
Epoch 9/100
8000/8000 [==============================] - 0s 52us/step - loss: 0.3571 - accuracy: 0.8530
Epoch 10/100
8000/8000 [==============================] - 0s 56u

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

Exit: 1 : Yes 
Exit: 0 : No

##### Solution:

In [30]:
model.predict(sc.transform([[1,0,0,600,1,40,3,6000,2,1,1,50000]]))

array([[0.03603366]], dtype=float32)

the o/p will always will come in probability whether the customer will stay or leave.


In this case, it shows 0.03 prob that the customer will leave

In [32]:
print(model.predict(sc.transform([[1,0,0,600,1,40,3,6000,2,1,1,50000]]))>0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

# Score

In [80]:
y_pred = model.predict(X_test)
y_pred

array([[0.28075057],
       [0.41050506],
       [0.16406044],
       ...,
       [0.16991383],
       [0.15520525],
       [0.29108447]], dtype=float32)

In [81]:
Predcited_Y=[]
for each in y_pred.flatten():
    if each > 0.5:
        Predcited_Y.append(1)
    else:
        Predcited_Y.append(0)

In [82]:
M[:6]

[0, 0, 0, 0, 0, 1]

In [83]:
print(type(Predcited_Y))
print(type(y_test))

<class 'list'>
<class 'numpy.ndarray'>


In [84]:
comparison=pd.DataFrame({
    'Predicted' :np.array(Predcited_Y),
    'Actual'  : y_test.flatten()
})

In [85]:
comparison.head(10)

Predicted  Actual
0          0       0
1          0       1
2          0       0
3          0       0
4          0       0
5          1       1
6          0       0
7          0       0
8          0       1
9          1       1

In [86]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,Predcited_Y)

0.8605