<h2 style="color:green" align="center">Predicting the probability whether a customer will buy (y) a particular car or not using logistic regression</h2>

# Importing Libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
df=pd.read_csv("Social_Network_Ads.csv")

In [4]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

Based on the characteristics of a person you have to determine whether the person will buy a SUV or not

In [5]:
dumps=pd.get_dummies(df.Gender)

In [6]:
df=pd.concat([df,dumps],axis=1)

In [7]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased  Female  Male
0  15624510    Male   19            19000          0       0     1
1  15810944    Male   35            20000          0       0     1
2  15668575  Female   26            43000          0       1     0
3  15603246  Female   27            57000          0       1     0
4  15804002    Male   19            76000          0       0     1

In [8]:
X=df.drop(columns=['User ID','Gender','Purchased','Female'])

In [9]:
X.head()

Age  EstimatedSalary  Male
0   19            19000     1
1   35            20000     1
2   26            43000     0
3   27            57000     0
4   19            76000     1

In [10]:
Y=df[['Purchased']]

In [11]:
Y.head()

Purchased
0          0
1          0
2          0
3          0
4          0

In [12]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
X=st.fit_transform(X)

In [13]:
X

array([[-1.78179743, -1.49004624,  1.02020406],
       [-0.25358736, -1.46068138,  1.02020406],
       [-1.11320552, -0.78528968, -0.98019606],
       ...,
       [ 1.17910958, -1.46068138, -0.98019606],
       [-0.15807423, -1.07893824,  1.02020406],
       [ 1.08359645, -0.99084367, -0.98019606]])

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,train_size=0.8)

In [15]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)

In [16]:
import warnings
warnings.filterwarnings("ignore")
model.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
Y_Pred=model.predict(X_test)

In [18]:
Y_Pred

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [19]:
Y_test.head()

Purchased
314          0
237          0
330          0
28           0
97           1

In [20]:
model.score(X_test,Y_test)

0.8375

In [21]:
Y_test.values

array([[0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1]], dtype=int64)

In [22]:
Y_Pred

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [23]:
type(Y_Pred)

numpy.ndarray

In [24]:
Y_test.values # 2D array
Y_tested=Y_test.values.flatten() # 1D array

In [25]:
Y_tested

array([0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [26]:
pd.DataFrame({
    'actual' : Y_tested,
    'pred' : Y_Pred
 })

actual  pred
0        0     0
1        0     0
2        0     0
3        0     0
4        1     0
5        0     0
6        1     0
7        1     1
8        1     1
9        1     1
10       0     0
11       0     0
12       0     0
13       1     0
14       0     0
15       0     0
16       0     0
17       1     0
18       1     1
19       0     1
20       0     0
21       1     1
22       0     0
23       0     0
24       0     0
25       1     1
26       0     0
27       0     0
28       1     1
29       0     0
..     ...   ...
50       0     0
51       0     0
52       0     0
53       0     0
54       1     1
55       1     0
56       1     1
57       0     0
58       1     1
59       1     1
60       0     0
61       0     0
62       1     1
63       0     0
64       1     1
65       1     1
66       0     0
67       1     1
68       0     0
69       0     0
70       0     1
71       0     0
72       0     1
73       1     0
74       0     0
75       0     0
76       0     0
77       0     0
78       0     0
79       1     1

[80 rows x 2 columns]