<h1 style='color:blue;' align='center'>KFold Cross Validation</h2>

In [39]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_digits
digits=load_digits()

In [40]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(digits.data,digits.target,test_size=0.2)


In [42]:
digits.data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [43]:
len(X_train)

1437

In [44]:
import warnings
warnings.filterwarnings("ignore")

**Evaluating performance of 3 models - Logistic,SVM,RandomForest**

**Logistic Regression**

In [45]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,Y_train)
lr.score(X_test,Y_test)

0.9555555555555556

**SVM**

In [46]:
from sklearn.svm import SVC
sv=SVC()
sv.fit(X_train,Y_train)
sv.score(X_test,Y_test)

0.5611111111111111

**Random Forest**

In [47]:
from sklearn.ensemble import RandomForestClassifier
rc=RandomForestClassifier(n_estimators=50)
rc.fit(X_train,Y_train)
rc.score(X_test,Y_test)

0.9527777777777777

RandomForest is working better till now from above obesrvations

The distribution of samples in X_train and X_test is not uniform
If we repeat the process, the distribution of samples in X_train and X_test will change
This will make changes in the score of each model
So, let's see.

In [48]:
from sklearn.model_selection import train_test_split
X1_train,X1_test,Y1_train,Y1_test=train_test_split(digits.data,digits.target,test_size=0.2)

**Logistic Regression**

In [49]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X1_train,Y1_train)
lr.score(X1_test,Y1_test)

0.9611111111111111

**SVM**

In [50]:
from sklearn.svm import SVC
sv=SVC()
sv.fit(X1_train,Y1_train)
sv.score(X1_test,Y1_test)

0.4388888888888889

###### The score of SVC fluctuates a lot.

**Random Forest**

In [53]:
from sklearn.ensemble import RandomForestClassifier
rc=RandomForestClassifier(n_estimators=50)
rc.fit(X1_train,Y1_train)
rc.score(X1_test,Y1_test)

0.9805555555555555

<h2 style='color:purple'>KFold cross validation</h2>

**Basic example**

In [54]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf1=KFold(n_splits=4)

In [55]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [56]:
for x,y in kf1.split([12,23,33,42,354,65,57,585,59]):
    print(x,y) 
# Prints the index

[3 4 5 6 7 8] [0 1 2]
[0 1 2 5 6 7 8] [3 4]
[0 1 2 3 4 7 8] [5 6]
[0 1 2 3 4 5 6] [7 8]


In [57]:
for x,y in kf1.split(digits.data):
    print(x,y)

[ 450  451  452 ... 1794 1795 1796] [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 23

**Use KFold for our digits example**

Instead of writing the code for different types of model every time, let's create a function

In [68]:
def get_score(model,X_train,X_test,Y_train,Y_test):
    model.fit(X_train,Y_train)
    return model.score(X_test,Y_test)

**Logistic Regression Score**

In [69]:
get_score(lr,X_train,X_test,Y_train,Y_test)

0.9093959731543624

**SVM Score**

In [70]:
get_score(sv,X_train,X_test,Y_train,Y_test)

0.4597315436241611

**Random Forest Score**

In [77]:
get_score(rc,X_train,X_test,Y_train,Y_test)

0.9261744966442953

In [78]:
from sklearn.model_selection import StratifiedKFold
sKF=StratifiedKFold(n_splits=3) 

In [79]:
scores_logistic=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in sKF.split(digits.data,digits.target):
    X_train,X_test,Y_train,Y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],\
    digits.target[test_index]
    scores_logistic.append(get_score(lr,X_train,X_test,Y_train,Y_test))
    scores_svm.append(get_score(sv,X_train,X_test,Y_train,Y_test))
    scores_rf.append(get_score(rc,X_train,X_test,Y_train,Y_test))

    

In [80]:
scores_logistic

[0.8953488372093024, 0.9499165275459098, 0.9093959731543624]

In [81]:
scores_svm

[0.39368770764119604, 0.41068447412353926, 0.4597315436241611]

In [82]:
scores_rf

[0.9285714285714286, 0.9532554257095158, 0.9278523489932886]

<h2 style='color:purple'>cross_val_score function</h2>

In [86]:
from sklearn.model_selection import cross_val_score
#--> press shift+tab on cross_val_score to see the parameters:
#-->    estimator
#-->    X
#-->    y


**Logistic regression model performance using cross_val_score**

In [87]:
cross_val_score(LogisticRegression(),X_test,Y_test)

array([0.90547264, 0.87437186, 0.86734694])

**svm model performance using cross_val_score**

In [88]:
cross_val_score(SVC(),X_test,Y_test)

array([0.20895522, 0.2160804 , 0.22959184])

**random forest performance using cross_val_score**

In [90]:
cross_val_score(RandomForestClassifier(),X_test,Y_test)

array([0.87064677, 0.83919598, 0.81122449])

<h1 style='color:green;' align='center'>Problem 2</h2>

Use iris flower dataset from sklearn library and use cross_val_score against following
models to measure the performance of each. In the end figure out the model with best performance,
1. Logistic Regression
2. SVM
3. Decision Tree
4. Random Forest

In [91]:
import numpy as np
from sklearn.linear_model import LogisticRegression
lrmodel=LogisticRegression()
from sklearn.svm import SVC
svcmodel=SVC()
from sklearn.tree import DecisionTreeClassifier
dtmodel=DecisionTreeClassifier()
from sklearn.ensemble import RandomForestClassifier
rfmodel=RandomForestClassifier()

In [92]:
from sklearn.datasets import load_iris
flowers=load_iris()

In [93]:
dir(flowers)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [94]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import StratifiedKFold
sKF=StratifiedKFold(n_splits=3)

In [95]:
def score_calculator(model,X_train,X_test,Y_train,Y_test):
    model.fit(X_train,Y_train)
    return model.score(X_test,Y_test)

In [96]:
score_calculator

<function __main__.score_calculator(model, X_train, X_test, Y_train, Y_test)>

In [98]:
lr1=[]
svm1=[]
dt1=[]
rf1=[]
for train_index,test_index in sKF.split(flowers.data,flowers.target):
    X_train,X_test,Y_train,Y_test=flowers.data[train_index],flowers.data[test_index],flowers.target[train_index],\
    flowers.target[test_index]
    lr1.append(score_calculator(lrmodel,X_train,X_test,Y_train,Y_test))
    svm1.append(score_calculator(svcmodel,X_train,X_test,Y_train,Y_test))
    dt1.append(score_calculator(dtmodel,X_train,X_test,Y_train,Y_test))
    rf1.append(score_calculator(rfmodel,X_train,X_test,Y_train,Y_test))


    

**Logistic Regression Score**

In [99]:
lr1

[0.9607843137254902, 0.9215686274509803, 0.9583333333333334]

In [100]:
lr11=np.array(lr1)
lr11.mean()

0.9468954248366014

**SVM Score**

In [101]:
svm1

[0.9803921568627451, 0.9607843137254902, 0.9791666666666666]

In [102]:
svm11=np.array(svm1)
svm11.mean()

0.9734477124183006

**Decision Tree Score**

In [116]:
dt1

[0.9803921568627451, 0.9215686274509803, 1.0]

In [104]:
dt11=np.array(dt1)
dt11.mean()

0.9673202614379085

**Random Forest Score**

In [117]:
rf1

[0.9803921568627451, 0.9411764705882353, 0.9791666666666666]

In [118]:
rf11=np.array(rf1)
rf11.mean()

0.9669117647058822

<h2 style='color:purple'>Using cross_val_score function</h2

In [119]:
from sklearn.model_selection import cross_val_score

**Logistic Regression Score**

In [120]:
cross_val_score(LogisticRegression(),flowers.data,flowers.target)

array([0.96078431, 0.92156863, 0.95833333])

In [121]:
a1=cross_val_score(LogisticRegression(),flowers.data,flowers.target)
a1.mean()

0.9468954248366014

**SVM Score**

In [122]:
cross_val_score(SVC(),flowers.data,flowers.target)

array([0.98039216, 0.96078431, 0.97916667])

In [123]:
b1=cross_val_score(SVC(),flowers.data,flowers.target)
b1.mean()

0.9734477124183006

**Decision Tree Score**

In [124]:
cross_val_score(DecisionTreeClassifier(),flowers.data,flowers.target)

array([0.98039216, 0.92156863, 1.        ])

In [125]:
c1=cross_val_score(DecisionTreeClassifier(),flowers.data,flowers.target)
c1.mean()

0.960375816993464

**Random Forest Score**

In [126]:
cross_val_score(RandomForestClassifier(),flowers.data,flowers.target)

array([0.98039216, 0.94117647, 0.95833333])

In [127]:
d1=cross_val_score(RandomForestClassifier(),flowers.data,flowers.target)
d1.mean()

0.9599673202614379

**Best score so far is from SVM: 0.9734477124183006**